### ISSUE TITLE
Reaper tries to de-register Consul server node

### ISSUE THREAD

**Issue by dustinchilson** [rogeralsing/Microphone#31]
Given an 3 node Consul cluster with 1 consul client and you take one of the Consul servers down the Reaper loop tries to de-register the consul service from the cluster.

https://i.imgur.com/GYcIoy8.png

When the consul server returns to the cluster these errors are no longer encountered.

**Comment by rogeralsing** [comment]
Thanks for reporting this.
In retrospect after having running Microphone for some time, I think that having the reaper deregistering services in consul was a mistake.
It should probably be left to some external service / admin to manage what should be removed.
Removing services that are currently unavailable might be too trigger happy, they might just be unavailable due to network glitches.

Does this sound reasonable?

**Comment by dustinchilson** [comment]
I agree it might be better to let Consul be the hub and let another monitoring / deployment like service manage the services.

**Comment by rogeralsing** [comment]
Reaper have been removed and Microphone no longer care how services are cleaned up, that is left for end user to handle.
